export const filterOptions = {
  country: [
    { id: "ae", name: "United Arab Emirates" },
    { id: "ar", name: "Argentina" },
    { id: "at", name: "Austria" },
    { id: "au", name: "Australia" },
    { id: "be", name: "Belgium" },
    { id: "bg", name: "Bulgaria" },
    { id: "br", name: "Brazil" },
    { id: "ca", name: "Canada" },
    { id: "ch", name: "Switzerland" },
    { id: "cn", name: "China" },
    { id: "co", name: "Colombia" },
    { id: "cu", name: "Cuba" },
    { id: "cz", name: "Czech Republic" },
    { id: "de", name: "Germany" },
    { id: "eg", name: "Egypt" },
    { id: "fr", name: "France" },
    { id: "gb", name: "United Kingdom" },
    { id: "gr", name: "Greece" },
    { id: "hk", name: "Hong Kong" },
    { id: "hu", name: "Hungary" },
    { id: "id", name: "Indonesia" },
    { id: "ie", name: "Ireland" },
    { id: "il", name: "Israel" },
    { id: "in", name: "India" },
    { id: "it", name: "Italy" },
    { id: "jp", name: "Japan" },
    { id: "kr", name: "South Korea" },
    { id: "lt", name: "Lithuania" },
    { id: "lu", name: "Luxembourg" },
    { id: "lv", name: "Latvia" },
    { id: "ma", name: "Morocco" },
    { id: "mx", name: "Mexico" },
    { id: "my", name: "Malaysia" },
    { id: "ng", name: "Nigeria" },
    { id: "nl", name: "Netherlands" },
    { id: "no", name: "Norway" },
    { id: "nz", name: "New Zealand" },
    { id: "ph", name: "Philippines" },
    { id: "pl", name: "Poland" },
    { id: "pt", name: "Portugal" },
    { id: "ro", name: "Romania" },
    { id: "rs", name: "Serbia" },
    { id: "sa", name: "Saudi Arabia" },
    { id: "se", name: "Sweden" },
    { id: "sg", name: "Singapore" },
    { id: "sk", name: "Slovakia" },
    { id: "th", name: "Thailand" },
    { id: "tr", name: "Turkey" },
    { id: "tw", name: "Taiwan" },
    { id: "ua", name: "Ukraine" },
    { id: "us", name: "United States" },
    { id: "ve", name: "Venezuela" },
    { id: "za", name: "South Africa" },
  ],
  category: [
    "Business",
    "Entertainment",
    "General",
    "Health",
    "Science",
    "Sports",
    "Technology",
  ].map((cat) => cat.toLowerCase()),
  sources: [
    { id: "abc-news", name: "ABC News" },
    { id: "bbc-news", name: "BBC News" },
    { id: "cnn", name: "CNN" },
    { id: "fox-news", name: "Fox News" },
    { id: "the-huffington-post", name: "The Huffington Post" },
    { id: "the-new-york-times", name: "The New York Times" },
    { id: "reuters", name: "Reuters" },
    { id: "the-wall-street-journal", name: "The Wall Street Journal" },
    { id: "the-washington-post", name: "The Washington Post" },
    { id: "usa-today", name: "USA Today" },
    { id: "mako", name: "Mako" },
  ], // Add your sources here
};

export const additionalFilterOptions = {
  sortBy: [
    { id: "relevancy", name: "Relevancy" },
    { id: "popularity", name: "Popularity" },
    { id: "publishedAt", name: "Published At" },
  ],
  dates: {
    from: [], // This could be a date picker component for the start date
    to: [], // This could be another date picker component for the end date
  },
  sources: [
    { id: "abc-news", name: "ABC News" },
    { id: "bbc-news", name: "BBC News" },
    { id: "cnn", name: "CNN" },
    { id: "fox-news", name: "Fox News" },
    { id: "the-huffington-post", name: "The Huffington Post" },
    { id: "the-new-york-times", name: "The New York Times" },
    { id: "reuters", name: "Reuters" },
    { id: "the-wall-street-journal", name: "The Wall Street Journal" },
    { id: "the-washington-post", name: "The Washington Post" },
    { id: "usa-today", name: "USA Today" },
    { id: "mako", name: "Mako" },
  ], // Add your sources here
  language: [
    { id: "en", name: "English" },
    { id: "es", name: "Spanish" },
    //...other languages
  ],
};
